#!/usr/bin/env python
# PYTHON_ARGCOMPLETE_OK
""" gls: git-listings

A ls-clone that lists a content of a folder using the logic of ls,
but displayes the git-status through the colors."""

import argparse
import glob
import sys

import glslib

descriptions = []
for description in sorted(glslib.config.description.keys()):

    code = glslib.config.description[description]
    mapping = glslib.config.mapping[code]
    color = glslib.config.color[mapping]
    description = "     * " + color + description
    description = description + glslib.config.color["white"]
    descriptions.append(description)

descriptions = "\n".join(descriptions)

parser = argparse.ArgumentParser(
    formatter_class=argparse.RawTextHelpFormatter,
    description="""\
List information in FILE and color them by git local status""",
    epilog="""The default setting is to hide files that are
ignored and untracked.
Tracked hidden files are always visible.

The colors have the following meaning:
"""+descriptions+"""
Tracked files without change are white.""",
    usage="%(prog)s [-aAdihruvw] FILE",
    add_help=False
    )

parser.add_argument("FILE", nargs="*",
                    help="files and foldes to be listed").completer=\
    lambda prefix, **kws: glob.glob("*")
parser.add_argument("-a", "--all", action="store_true",
                    help="show ignored and hidden")
parser.add_argument("-r", "--recursive", action="store_true",
                    help="list subdirectories recursively")
parser.add_argument("-l", "--long", action="store_true",
                    help="use a long listing format")
parser.add_argument("-h", "--human-readable", action="store_true",
                    help="print human readable sizes")
parser.add_argument("-u", "--untracked", action="store_true",
                    help="hide untracked files")
parser.add_argument("-i", "--ignored", action="store_true",
                    help="show ignored files")
parser.add_argument("-w", "--width", type=int,
                    help="assume screen width instead of current value")
parser.add_argument("-H", "--help", action="store_true",
                    help="display help message")

try:
    import argcomplete
    argcomplete.autocomplete(parser)
except:
    pass


if __name__ == "__main__":

    args = parser.parse_args()
    if args.help:
        parser.print_help()
    else:
        out = glslib.main(args)
        print(out)

